Reverting part of 3081f3440 . Caused regression...
java.lang.IllegalStateException: Duplicate key com.liferay.oauth2.provider.web.internal.display.context.AssignScopesModel$Relations